def shared_pods
    pod 'Crashlytics'
    pod 'Crashlytics-FPCustomHandler', :path => '../'
end

target 'CustomCrashHandler' do
    shared_pods
end

target 'CustomCrashHandlerTests' do
    shared_pods
end
